# @package _global_

dataset:
  view_sampler:
    num_context_views: 2
    num_target_views: 4
    min_distance_between_context_views: 45
    max_distance_between_context_views: 90 # 45 # 90
    max_distance_to_context_views: 0 # 45 # 90
    context_gap_warm_up_steps: 75_000 # 50_000   # 150_000
    target_gap_warm_up_steps: 75_000 # 50_000
    initial_min_distance_between_context_views: 25
    initial_max_distance_between_context_views: 45 # 25 # 45
    initial_max_distance_to_context_views: 0
