
# @package _global_

defaults:
  - override /dataset: re10k

dataset:
  view_sampler:
    index_path: assets/evaluation_index/re10k_video_all.json


evaluation:
  weights: "/BS/grl-co3d/work/models--naver--MASt3R_ViTLarge_BaseDecoder_512_catmlpdpt_metric/snapshots/06e7259f34c3060f322df5cb0c7b9094f57e41fc"
  
  methods:       
  
    # - name: 52k
    #   key: test_extra_52k
    #   path: outputs/base_sd_vae_nosch_ddim_no_rayenc_3d_hb_video/test_video_52k/video
  
    # - name: 218K
    #   key: test_video_218k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_video/test_video_218k/video

    # - name: 474K
    #   key: test_video_474k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_video/test_video_474k/video

    # - name: 608k
    #   key: test_video_608k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_video/test_video_608k/video
    
    # - name: 946k
    #   key: test_video_946k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_video/test_video_946k/video
    
    # - name: 1206k
    #   key: test_video_1206k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_video/test_video_1206k/video

    # - name: 1546k
    #   key: test_video_1546k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_video/test_video_1456k/video

    # - name: 2000k
    #   key: test_video_2000k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_video/test_video_2000k/video

    # - name: SD-2 + RayEnc
    #   key: test_video_2000k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_video/test_video_2000k/video


    - name: GenWarp
      key: genwarp_fixed
      path: genwarp/video

    - name: Ours
      key: test_video_1679k_3d
      path: outputs/base_sd_vae_nosch_ddim_no_rayenc_3d_video/test_video_1679k/video

    - name: DFM
      key: dfm
      path: /BS/grl-masim-data/work/DFM/outputs/dfm

    # - name: cfg_3
    #   key: test_extra_3
    #   path: outputs/base_sd_vae_nosch_ddim_no_rayenc_3d_test/test_extra_738k/test
    
    # - name: cfg_5
    #   key: test_extra_5
    #   path: outputs/base_sd_vae_nosch_ddim_no_rayenc_3d_test/test_extra_5/test
    
    # - name: cfg_7
    #   key: test_extra_7
    #   path: outputs/base_sd_vae_nosch_ddim_no_rayenc_3d_test/test_extra_7/test
    
    # - name: cfg_9
    #   key: test_extra_9
    #   path: outputs/base_sd_vae_nosch_ddim_no_rayenc_3d_test/test_extra_9/test
    
    # - name: m1
    #   key: test_extra_1000k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_no_rayenc_test/test_extra_1000k/test

    # - name: m1
    #   key: test_extra_946k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_test/test_extra_946k/test

    # - name: m2
    #   key: test_extra_938k
    #   path: /BS/grl-co3d/work/mv_diff/outputs/base_sd_vae_nosch_ddim_no_rayenc_3d_test/test_extra_938k/test


  types: pairwise
  img_size: 224
  output_path: /BS/grl-co3d/work/mv_diff
  gt_directory: gt_images_video_all
  mvssim_cfg: 
    subsample_or_initxy1: 8
    corres_weighting: true
    conf_weighting: true
    confidence_key: "conf"
    reduction: null
    return_matches: true
    compute_intrinsics: false
output_metrics_path: baselines/evaluation_metrics.json
per_scene_metrics_path: baselines/per_scene_metrics.json
