defaults:
  - dataset: re10k
  - model/scheduler: ddim
  - model/denoiser: mv_unet
  - model/autoencoder: kl

scene_id: null
mode: train
seed: null

hydra:
  run:
    dir: ""   # override!

wandb:
  project: mvdiff
  entity: null
  mode: online
  activated: true

freeze:
  denoiser: false
  autoencoder: true

model:
  ema: false
  ray_encodings: 
    num_origin_octaves: 10
    num_direction_octaves: 8
  use_cfg: true
  cfg_scale: 3.0
  cfg_train: true
  use_ray_encoding: true
  srt_ray_encoding: false
  use_plucker: false
  use_ema_sampling: false
  enable_xformers_memory_efficient_attention: false

dataset:
  overfit_to_scene: null

data_loader:
  # Avoid having to spin up new processes to print out visualizations.
  train:
    num_workers: 16
    persistent_workers: true
    batch_size: 6
    seed: null
  test:
    num_workers: 16
    persistent_workers: false
    batch_size: 1
    seed: 0
  val:
    num_workers: 16
    persistent_workers: false
    batch_size: 8
    seed: 0

checkpointing:
  load: null
  resume: false
  every_n_train_steps: 1000
  save_top_k: 1

train:
  step_offset: 0
  cfg_train: true

test:
  output_path: outputs/test
  sampling_mode: null
  limit_frames: null
  num_anchors_views: 4
  output_dir: ""

trainer:
  max_steps: 1_000_001
  val_check_interval: 5000
  task_steps: null
  gradient_clip_val: 0.1 # 0.5
  precision: null
  validate: true
  accumulate_grad_batches: 2
  limit_test_batches: 32
  strategy: 'ddp_find_unused_parameters_true'