defaults:
  - view_sampler: bounded

name: co3d_serialized
roots: [/BS/databases28/co3dv1_compressed]
make_baseline_1: true
augment: true
scene: hydrant
planes: [0.5, 40.0]

# splits
train_split_json: assets/dataset_splits/co3d_hydrant_train.json
eval_split_json: assets/dataset_splits/co3d_hydrant_eval.json

image_shape: [256, 256]
background_color: [0.0, 0.0, 0.0]
cameras_are_circular: true

baseline_epsilon: 1e-3
max_fov: 100.0
overfit_to_scene: null