defaults:
  - view_sampler: random

name: objaverse
roots: [/BS/databases28/objaverse]
augment: true
planes: [0.8, 3.2]
num_views: 12

# splits
train_split_json: assets/dataset_splits/objaverse_train.json
eval_split_json: assets/dataset_splits/objaverse_eval.json

image_shape: [256, 256]
background_color: [1.0, 1.0, 1.0]
cameras_are_circular: true

fov: 49.134342641202636