name: bounded

num_context_views: 2
num_target_views: 0
min_distance_between_context_views: 0
max_distance_between_context_views: null
max_distance_to_context_views: 0
context_gap_warm_up_steps: 0
target_gap_warm_up_steps: 0
initial_min_distance_between_context_views: 0
initial_max_distance_between_context_views: null
initial_max_distance_to_context_views: 0
