name: ddim
pretrained_from: null
num_inference_steps: 70
num_train_timesteps: 1000

# Refer to https://huggingface.co/docs/diffusers/v0.4.1/en/api/schedulers#diffusers.DDIMScheduler
kwargs:
  num_train_timesteps: 1000
  clip_sample: False
  prediction_type: "epsilon"
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: "linear"
  trained_betas: null
  set_alpha_to_one: True
  steps_offset: 0