name: ddpm
pretrained_from: null
num_inference_steps: 1000
num_train_timesteps: 1000

# Refer to https://huggingface.co/docs/diffusers/en/api/schedulers/ddpm#diffusers.DDPMScheduler
kwargs:
  num_train_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  beta_schedule: "linear"
  trained_betas: None
  variance_type: "fixed_small"
  clip_sample: true
  prediction_type: "epsilon"
  thresholding: false
  dynamic_thresholding_ratio: 0.995
  clip_sample_range: 1.0
  sample_max_value: 1.0
  timestep_spacing: "leading"
  steps_offset: 0
  rescale_betas_zero_snr: false