name: multiview_hybrid

self_attention:
  patch_size: 4
  num_octaves: 10
  num_heads: 8
  d_token: 128
  d_mlp_multiplier: 1
num_octaves: 10
num_heads: 8
num_samples: [32, 16, 8, 4]
d_mlp_multiplier: 1
grid_sample_type: "bilinear"